
blueprint:
  name: Tesla Morning Preheat (Final: Binary Cable Sensor, Snapshot & Restore)
  description: >
    Starts Tesla climate preconditioning at a scheduled time on selected weekdays,
    only if the Tesla is in the target zone AND the charge cable binary sensor is ON (connected).
    Snapshots original climate state and restores it when:
      • The cable is unplugged (binary sensor goes OFF) before timeout, OR
      • The countdown timeout expires.
  domain: automation

  input:
    preheat_time:
      name: Preheat time
      selector: { time: {} }

    weekdays:
      name: Days to run
      default: [mon, tue, wed, thu, fri]
      selector:
        select:
          options: [mon, tue, wed, thu, fri, sat, sun]
          multiple: true

    tesla_location_tracker:
      name: Tesla device tracker (reports zone as state)
      selector:
        entity:
          filter:
            - domain: device_tracker

    target_zone:
      name: Target zone name
      default: "Home"
      selector: { text: {} }

    charge_cable_binary_sensor:
      name: Charge cable binary sensor (ON=Connected, OFF=Disconnected)
      selector:
        entity:
          filter:
            - domain: binary_sensor

    climate_entity:
      name: Tesla climate entity (REQUIRED)
      description: e.g., climate.<your_vehicle>
      selector:
        entity:
          filter:
            - domain: climate

    cabin_setpoint:
      name: Cabin temperature setpoint (°C)
      default: 21
      selector:
        number:
          min: 16
          max: 28
          step: 0.5
          unit_of_measurement: "°C"

    stop_after_minutes:
      name: Stop climate after (minutes)
      description: Countdown before restoring climate; set 0 to disable timer (still restores on cable unplug)
      default: 30
      selector:
        number:
          min: 0
          max: 180
          step: 5
          unit_of_measurement: "min"

mode: single

variables:
  v_presence: !input tesla_location_tracker
  target_zone: !input target_zone
  v_cable: !input charge_cable_binary_sensor
  v_climate: !input climate_entity
  v_setpoint: !input cabin_setpoint
  v_stop_after: !input stop_after_minutes

trigger:
  - platform: time
    at: !input preheat_time

condition:
  - condition: time
    weekday: !input weekdays
  - condition: template
    value_template: "{{ states(v_presence) == target_zone }}"
  - condition: state
    entity_id: !input charge_cable_binary_sensor
    state: "on"   # ON means the cable is connected

action:
  # Snapshot original climate state for precise restore
  - alias: "Snapshot original climate"
    service: scene.create
    data:
      scene_id: tesla_preheat_before
      snapshot_entities:
        - !input climate_entity

  # Start climate and set setpoint
  - alias: "Start climate"
    service: climate.turn_on
    target:
      entity_id: !input climate_entity

  - alias: "Set cabin setpoint"
    service: climate.set_temperature
    target:
      entity_id: !input climate_entity
    data:
      temperature: !input cabin_setpoint

  # --- Wait for cable unplug OR timeout ---
  - alias: "Wait for unplug or timeout"
    choose:
      - conditions: "{{ v_stop_after|int > 0 }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input charge_cable_binary_sensor
                from: "on"
                to: "off"
            timeout:
              minutes: !input stop_after_minutes
            continue_on_timeout: true

          # Restore on either unplug or timeout
          - alias: "Restore original climate"
            service: scene.turn_on
            target:
              entity_id: scene.tesla_preheat_before
    default:
      # No timer: just wait for unplug
      - wait_for_trigger:
          - platform: state
            entity_id: !input charge_cable_binary_sensor
            from: "on"
            to: "off"
        continue_on_timeout: false

      - alias: "Restore original climate"
        service: scene.turn_on
        target:
          entity_id: scene.tesla_preheat_before
