blueprint:
  name: Tesla Morning Preheat (Stop on Cable Disconnect or Timeout)
  description: >
    Starts Tesla climate preconditioning at a scheduled time on selected weekdays,
    only if the Tesla is in the target zone AND charger is Connected.
    Snapshots original climate state and restores it when:
      • Cable is unplugged before timeout, OR
      • Timeout expires.
  domain: automation

  input:
    preheat_time:
      name: Preheat time
      selector: { time: {} }

    weekdays:
      name: Days to run
      default: [mon, tue, wed, thu, fri]
      selector:
        select:
          options: [mon, tue, wed, thu, fri, sat, sun]
          multiple: true

    tesla_location_tracker:
      name: Tesla device tracker
      selector:
        entity:
          filter:
            - domain: device_tracker

    target_zone:
      name: Target zone name
      default: "Home"
      selector: { text: {} }

    charger_state_sensor:
      name: Charger state sensor
      description: Shows 'Connected' when cable is plugged
      selector:
        entity:
          filter:
            - domain: sensor

    climate_entity:
      name: Tesla climate entity
      description: e.g., climate.<your_vehicle>
      selector:
        entity:
          filter:
            - domain: climate

    cabin_setpoint:
      name: Cabin temperature setpoint (°C)
      default: 21
      selector:
        number:
          min: 16
          max: 28
          step: 0.5
          unit_of_measurement: "°C"

    stop_after_minutes:
      name: Stop climate after (minutes)
      default: 30
      selector:
        number:
          min: 5
          max: 180
          step: 5
          unit_of_measurement: "min"

mode: single

variables:
  v_presence: !input tesla_location_tracker
  target_zone: !input target_zone
  v_charger: !input charger_state_sensor
  v_climate: !input climate_entity
  v_setpoint: !input cabin_setpoint
  v_stop_after: !input stop_after_minutes

trigger:
  - platform: time
    at: !input preheat_time

condition:
  - condition: time
    weekday: !input weekdays
  - condition: template
    value_template: "{{ states(v_presence) == target_zone }}"
  - condition: state
    entity_id: !input charger_state_sensor
    state: "Connected"

action:
  # Snapshot original climate state
  - service: scene.create
    data:
      scene_id: tesla_preheat_before
      snapshot_entities:
        - !input climate_entity

  # Start climate and set setpoint
  - service: climate.turn_on
    target: { entity_id: !input climate_entity }

  - service: climate.set_temperature
    target: { entity_id: !input climate_entity }
    data:
      temperature: !input cabin_setpoint

  # Wait for cable disconnect OR timeout
  - wait_for_trigger:
      - platform: state
        entity_id: !input charger_state_sensor
        from: "Connected"
    timeout:
      minutes: !input stop_after_minutes
    continue_on_timeout: true

  # Restore original climate state
  - service: scene.turn_on
    target: { entity_id: scene.tesla_preheat_before }
